export const WORKFLOW_TYPE = {
  NEW_INBOUND_CONVERSATIONS: 'NEW_INBOUND_CONVERSATIONS',
  ANY_INBOUND_MESSAGES: 'ANY_INBOUND_MESSAGES',
  CONVERSATION_CLOSING: 'CONVERSATION_CLOSING',
};
export const WORKFLOW_LISTEN_FOR = {
  ALL_MESSAGE: 'ALL_MESSAGE',
  KEY_WORDS: 'KEY_WORDS',
};
export const WORKFLOW_STRATEGY = {
  MESSAGE: 'MESSAGE',
  CAMPAIGN: 'CAMPAIGN',
};

export const WORKFLOW_ACTIVE_DURING = {
  ALL_TIMES: 'ALL_TIMES',
  SET_TIME_FRAMES: 'SET_TIME_FRAME',
};
